### ISSUE TITLE
--skip-pre option does not skip pre-request scripts at collection or folder level

### ISSUE THREAD

**Issue by MopsiMauser** [grafana/postman-to-k6#105]
Hi,

when using the --skip-pre option the converter does not remove the pre-request scripts at the collection or folder level. I attached a postman collection and the converted k6 script. I just had to change the extensions because github refuses to upload json and js files.

Command Line: postman-to-k6 TestCollection.postman_collection.json -o TestCollection.js --skip-pre

Best Regards

[TestCollection.js.txt](https://github.com/k6io/postman-to-k6/files/6586512/TestCollection.js.txt)
[TestCollection.postman_collection.json.txt](https://github.com/k6io/postman-to-k6/files/6586513/TestCollection.postman_collection.json.txt)

**Comment by thim81** [comment]
Hi @MopsiMauser 

I have provided a forked NPM package version that potential could fix your current issue plus I created a PR on the original postman-to-k6 package. Could you try it and give feedback if your problems is resolved?

To use the fix, you need to replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.6.1"
  }
```

This is a forked NPM package, to help overcome the issue. The current maintainers are quite overloaded by the acquisition of K6 by Grafana. By forking the repo & package, users can keep using new PR's & (security) fixes. At a later stage the changes can potentially be merged back in the original postman-to-k6 repo.

The [changelog](https://github.com/apideck-libraries/postman-to-k6/blob/main/CHANGELOG.md) contains the differences between the original package & the forked version.

**Comment by MopsiMauser** [comment]
Hi @thim81

 thank you for your effort!! I just tested it and it works now <3
